### ISSUE TITLE
Fails to start `tmux`

### ISSUE THREAD

**Issue by samth** [willghatch/rackterm#1]
Here's the output:

```
ignoring mode set - reset? #t, private? #t, params (1)
ignored escaped character: #\>
ignoring mode set - reset? #t, private? #t, params (12)
ignoring mode set - reset? #f, private? #t, params (25)
ignoring mode set - reset? #t, private? #t, params (1000)
ignoring mode set - reset? #t, private? #t, params (1006)
ignoring mode set - reset? #t, private? #t, params (1005)
ignored CSI terminator: c with params: (0)
ignored CSI terminator: > with params: (0)
ignoring mode set - reset? #f, private? #t, params (1004)
^Cuser break
  context...:
   /home/samth/sw/plt/extra-pkgs/gui-lib/gui-lib/mred/private/wx/common/queue.rkt:653:3
```

This is on Ubuntu 14.10.

**Comment by willghatch** [comment]
Is it just not drawing stuff, or what?  I'm in a weird transition state right now where I'm just using a laptop, and I don't have access to the virtual machines I normally have on my desktop, so I'm not in a great place to test it on all sorts of platforms right now.

I'm afraid my debugging output isn't super helpful even for me right now -- it just shows what I'm blatantly ignoring, (and none of those things are terribly important).

**Comment by samth** [comment]
It displays `4;1m` at the bottom, and nothing else.

**Comment by willghatch** [comment]
Hmm, I put together an ubuntu 14.10 VM, and I can't reproduce it so far.  First I tried running rackterm with the racket version in the 14.10 repository (5.3.6) and rackterm wouldn't run, then I tried with racket 6.1.1 and it's running fine (using tmux 1.9 from the 14.10 repo).  What version of Racket are you using?  Or what version of Tmux?  Perhaps your tmux version is starting with a weird sequence of escape codes that I'm not handling properly.

**Comment by samth** [comment]
I'm running Racket from git -- you can download a snapshot here: http://plt.eecs.northwestern.edu/snapshots/. On 6.1.1 it works correctly.

**Comment by willghatch** [comment]
Hmm, actually I've been running the git version on my laptop.  It works for
me on the latest commit (bf12a2bd... from the 7th), as well as the commit
I've been using for the last couple weeks (c8ff0c80... the second commit on
the 27th) on my Arch Linux box, and it seems to work fine with the latest
snapshot on my ubuntu 14.10 vm.  Do you have any special tmux
configuration?  I don't see a repository among those on your profile that
indicates that it is full of config/dotfiles.

**Comment by samth** [comment]
Here's my .tmux.conf file:

```
[samth@huor] cat ~/.tmux.conf 
set-window-option -g xterm-keys on
```

**Comment by samth** [comment]
But removing that doesn't fix the problem.

**Comment by willghatch** [comment]
Hmm... I'm fairly mystified, then.  It works fine for me with no tmux.conf or with my fairly modified one.  So I'm somewhat at a loss.  At some point I plan to decide on a good debugging approach to get more useful output, at which point a copy of the output of a run might be more valuable, but I'm not sure when I'll get around to that.  Do you, as a racket expert, have any good debugging tips?

**Comment by samth** [comment]
I just tried it on an installation from a snapshot, and it worked, so I don't know what's going on, but I'll close this issue.

**Comment by willghatch** [comment]
Also, are you using a recent version of rackterm?  If you run `echo $TERM` do you get `rackterm` as the output?  I only made it automatically set TERM recently, so if you have a weird TERM setting that might explain it acting differently.

**Comment by willghatch** [comment]
Anyway, thanks for the report and all.  If you have any other feedback I'll appreciate it.
